--CRIANDO A PROCEDURE
CREATE PROCEDURE DBO.STUDENT_GRADE_POINTS @STUDENT_GRADE VARCHAR(2) 
AS 
BEGIN
    SET NOCOUNT ON; 
--SELECIONANDO AS TUPLAS
    SELECT STUDENT.NAME AS "NOME DO ESTUDANTE", 
           STUDENT.DEPT_NAME AS "DEPARTAMENTO DO ESTUDANTE", 
           COURSE.TITLE AS "TÍTULO DO CURSO", 
           COURSE.DEPT_NAME AS "DEPARTAMENTO DO CURSO", 
           SECTION.SEMESTER AS "SEMESTRE DO CURSO", 
           SECTION.YEAR AS "ANO DO CURSO", 
           TAKES.GRADE AS "PONTUAÇÃO ALFANUMÉRICA",
--UTILIZANDO PARÂMETROS DE ENTRADA A+A
           IIF(TAKES.GRADE = 'A+', 4.0,
               IIF(TAKES.GRADE = 'A ', 3.7,
               IIF(TAKES.GRADE = 'A-', 3.3,
               IIF(TAKES.GRADE = 'B+', 3.0,
               IIF(TAKES.GRADE = 'B ', 2.7,
               IIF(TAKES.GRADE = 'B-', 2.3,
               IIF(TAKES.GRADE = 'C+', 2.0,
               IIF(TAKES.GRADE = 'C ', 1.7,
               IIF(TAKES.GRADE = 'C-', 1.3, 0))))))))) AS "PONTUAÇÃO NUMÉRICA"
    FROM STUDENT
    INNER JOIN DEPARTMENT ON STUDENT.DEPT_NAME = DEPARTMENT.DEPT_NAME 
    INNER JOIN COURSE ON DEPARTMENT.DEPT_NAME = COURSE.DEPT_NAME 
    INNER JOIN SECTION ON COURSE.COURSE_ID = SECTION.COURSE_ID 
    INNER JOIN TAKES ON STUDENT.ID = TAKES.ID 
--FILTRANDO AS TUPLAS.
    WHERE TAKES.GRADE = @STUDENT_GRADE
    GROUP BY STUDENT.NAME, STUDENT.DEPT_NAME, COURSE.TITLE, COURSE.DEPT_NAME, SECTION.SEMESTER, SECTION.YEAR, TAKES.GRADE;
END;
EXEC DBO.STUDENT_GRADE_POINTS 'A';


--CRIANDO A FUNÇÃO E COLOCANDO O NOME DO INSTRUTOR COMO PARÂMETRO DE ENTRADA.
CREATE FUNCTION DBO.RETURN_INSTRUCTOR_LOCATION (@NOMEINSTRUTOR VARCHAR(200))
--RETORNANDO ATRIBUTOS DA TUPLA
RETURNS TABLE
AS
RETURN
(
    SELECT
        "NOME DO INSTRUTOR",
        "CURSO MINISTRADO",
        "SEMESTRE DO CURSO",
        "ANO DO CURSO",
        PRÉDIO,
        "NÚMERO DA SALA"
    FROM
        DBO.INSTRUTORES_CURSOS_LOCALIZACAO
    WHERE
        "NOME DO INSTRUTOR" = @NOMEINSTRUTOR
);
